changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/checksum/
checksum:
  disable: false

# https://goreleaser.com/customization/build/
builds:
  -
    id: "post"
    main: ./cmd/bootstrap-post
    binary: bootstrapapp-post
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
  -
    id: "pre"
    main: ./cmd/bootstrap-pre-delete
    binary: bootstrapapp-pre-delete
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
  -
    id: "preinstall"
    main: ./cmd/bootstrap-pre-install
    binary: bootstrapapp-pre-install
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}


# https://goreleaser.com/customization/docker/
dockers:
  -
    ids:
      - post
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:latest-amd64"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-post:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: ".container/image/bootstrap-post/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    ids:
      - post
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:latest-arm64v8"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"
      - "tykio/tyk-k8s-bootstrap-post:{{ .Tag }}-arm64v8"
    goos: linux
    goarch: arm64
    dockerfile: ".container/image/bootstrap-post/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
  -
    ids:
      - pre
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:latest-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: ".container/image/bootstrap-pre-delete/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    ids:
      - pre
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:latest-arm64v8"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"
      - "tykio/tyk-k8s-bootstrap-pre-delete:{{ .Tag }}-arm64v8"
    goos: linux
    goarch: arm64
    dockerfile: ".container/image/bootstrap-pre-delete/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
  -
    ids:
      - preinstall
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:latest-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: ".container/image/bootstrap-pre-install/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    ids:
      - preinstall
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:latest-arm64v8"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}"
      - "tykio/tyk-k8s-bootstrap-pre-install:{{ .Tag }}-arm64v8"
    goos: linux
    goarch: arm64
    dockerfile: ".container/image/bootstrap-pre-install/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"

# https://goreleaser.com/customization/docker_manifest/
docker_manifests:
  - name_template: "tykio/tyk-k8s-bootstrap-post:latest"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:latest-amd64"
      - "tykio/tyk-k8s-bootstrap-post:latest-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-post:{{ .Tag }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:{{ .Tag }}-amd64"
      - "tykio/tyk-k8s-bootstrap-post:{{ .Tag }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-delete:latest"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:latest-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:latest-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-delete:{{ .Tag }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:{{ .Tag }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:{{ .Tag }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-install:latest"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:latest-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:latest-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{ if .Prerelease}}-{{ .Prerelease }}{{ end }}-arm64v8"

  - name_template: "tykio/tyk-k8s-bootstrap-pre-install:{{ .Tag }}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:{{ .Tag }}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:{{ .Tag }}-arm64v8"
