changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# https://goreleaser.com/customization/checksum/
checksum:
  disable: false

builds:
  -
    id: "preinstall"
    main: ./cmd/bootstrap-pre-install
    binary: bootstrapapp-pre-install
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
  -
    id: "postinstall"
    main: ./cmd/bootstrap-post
    binary: bootstrapapp-post
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}
  -
    id: "predelete"
    main: ./cmd/bootstrap-pre-delete
    binary: bootstrapapp-pre-delete
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.version={{.Version}}

# https://goreleaser.com/customization/docker/
dockers:
  - ids:
      - preinstall
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: ".container/image/bootstrap-pre-install/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - ids:
      - preinstall
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-arm64v8"
    goos: linux
    goarch: arm64
    dockerfile: ".container/image/bootstrap-pre-install/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
  -
    ids:
      - postinstall
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: ".container/image/bootstrap-post/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    ids:
      - postinstall
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-arm64v8"
    goos: linux
    goarch: arm64
    dockerfile: ".container/image/bootstrap-post/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
  - ids:
      - predelete
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-amd64"
    goos: linux
    goarch: amd64
    dockerfile: ".container/image/bootstrap-pre-delete/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - ids:
      - predelete
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-arm64v8"
    goos: linux
    goarch: arm64
    dockerfile: ".container/image/bootstrap-pre-delete/Dockerfile"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"

# https://goreleaser.com/customization/docker_manifest/
docker_manifests:
  - name_template: "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-install:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-arm64v8"
  - name_template: "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-amd64"
      - "tykio/tyk-k8s-bootstrap-post:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-arm64v8"
  - name_template: "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}"
    image_templates:
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-amd64"
      - "tykio/tyk-k8s-bootstrap-pre-delete:v{{ .Major }}.{{ .Minor }}{{.Prerelease}}-arm64v8"
