apiVersion: batch/v1
kind: Job
metadata:
  name: bootstrap-delployment
  namespace: tyk
  labels:
    app: bootstrap
spec:
  template:
    metadata:
      labels:
        app: bootstrap
    spec:
      restartPolicy: Never
      serviceAccountName: k8s-bootstrap-role
      containers:
        - name: bootstrap-tyk
          image: localhost:5001/bootstrap-tyk:0.31
          command: ['./app/bin/bootstrap-app']
          env:
            - name: TYK_ADMIN_FIRST_NAME
#              value: { { .Values.dash.adminUser.firstName | quote } }
              value: admin-name

            - name: TYK_ADMIN_LAST_NAME
#              value: { { .Values.dash.adminUser.lastName | quote } }

              value: admin-last-name
            - name: TYK_ADMIN_EMAIL
#              value: { { .Values.dash.adminUser.email | quote } }
              value: tyk-admin@tyk.io

            - name: TYK_ADMIN_PASSWORD
#              valueFrom:
#                secretKeyRef:
##                  name: { { .Release.Name } }-login-details
#                  name: tyk-pro-login-details
#                  key: TYK_PASS
              value: pass123and
            - name: TYK_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: TYK_DASHBOARD_PROTO
              value: http
            - name: TYK_DASHBOARD_SVC
              value: dashboard-svc-tyk-pro
            - name: TYK_DB_LISTENPORT
              value: "3000"
            - name: TYK_DB_LICENSEKEY
              value: "insertAValidDashboardLicenseKey"
            - name: TYK_ADMIN_SECRET
              value: "12345"
            - name: TYK_ORG_NAME
              value: Default name
            - name: TYK_ORG_CNAME
              value: tyk-portal.local

            - name: DASHBOARD_ENABLED
              value: "true"

            - name: OPERATOR_SECRET_ENABLED
              value: "true"
            - name: OPERATOR_SECRET_NAME
              value: "tyk-operator-conf"
            - name: ENTERPRISE_PORTAL_SECRET_ENABLED
              value: "true"
            - name: DEVELOPER_PORTAL_SECRET_ENABLED
              value: "true"
            - name: ENTERPRISE_PORTAL_SECRET_NAME
              value: "tyk-enterprise-portal-conf"
            - name: DEVELOPER_PORTAL_SECRET_NAME
              value: "tyk-dev-portal-conf"
            - name: BOOTSTRAP_DASHBOARD
              value: "true"
            - name: GATEWAY_ADDRESS
              value: http://gateway-svc-tyk-pro.tyk.svc.cluster.local:8080
            - name: BOOTSTRAP_PORTAL
              value: "true"
            - name: TYK_DASHBOARD_DEPLOY
              value: dashboard-tyk-pro

